using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PlatformSyncModel {

    [RealtimeProperty(1, true, true)]
    private bool _isSolidPlayer1;

    [RealtimeProperty(2, true, true)]
    private bool _isSolidPlayer2;

    [RealtimeProperty(3, true, true)]
    private static int _destroyedPlatforms;

    [RealtimeProperty(4, true, true)]
    private static bool _fail;

    [RealtimeProperty(5, true, true)]
    private bool _backupBool;

    [RealtimeProperty(6, true, true)]
    private float _backupFloat;

    [RealtimeProperty(7, true, true)]
    private int _backupInt;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PlatformSyncModel : RealtimeModel {
    public bool isSolidPlayer1 {
        get {
            return _isSolidPlayer1Property.value;
        }
        set {
            if (_isSolidPlayer1Property.value == value) return;
            _isSolidPlayer1Property.value = value;
            InvalidateReliableLength();
            FireIsSolidPlayer1DidChange(value);
        }
    }
    
    public bool isSolidPlayer2 {
        get {
            return _isSolidPlayer2Property.value;
        }
        set {
            if (_isSolidPlayer2Property.value == value) return;
            _isSolidPlayer2Property.value = value;
            InvalidateReliableLength();
            FireIsSolidPlayer2DidChange(value);
        }
    }
    
    public bool backupBool {
        get {
            return _backupBoolProperty.value;
        }
        set {
            if (_backupBoolProperty.value == value) return;
            _backupBoolProperty.value = value;
            InvalidateReliableLength();
            FireBackupBoolDidChange(value);
        }
    }
    
    public float backupFloat {
        get {
            return _backupFloatProperty.value;
        }
        set {
            if (_backupFloatProperty.value == value) return;
            _backupFloatProperty.value = value;
            InvalidateReliableLength();
            FireBackupFloatDidChange(value);
        }
    }
    
    public int backupInt {
        get {
            return _backupIntProperty.value;
        }
        set {
            if (_backupIntProperty.value == value) return;
            _backupIntProperty.value = value;
            InvalidateReliableLength();
            FireBackupIntDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PlatformSyncModel model, T value);
    public event PropertyChangedHandler<bool> isSolidPlayer1DidChange;
    public event PropertyChangedHandler<bool> isSolidPlayer2DidChange;
    public event PropertyChangedHandler<bool> backupBoolDidChange;
    public event PropertyChangedHandler<float> backupFloatDidChange;
    public event PropertyChangedHandler<int> backupIntDidChange;
    
    public enum PropertyID : uint {
        IsSolidPlayer1 = 1,
        IsSolidPlayer2 = 2,
        BackupBool = 5,
        BackupFloat = 6,
        BackupInt = 7,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _isSolidPlayer1Property;
    
    private ReliableProperty<bool> _isSolidPlayer2Property;
    
    private ReliableProperty<bool> _backupBoolProperty;
    
    private ReliableProperty<float> _backupFloatProperty;
    
    private ReliableProperty<int> _backupIntProperty;
    
    #endregion
    
    public PlatformSyncModel() : base(null) {
        _isSolidPlayer1Property = new ReliableProperty<bool>(1, _isSolidPlayer1);
        _isSolidPlayer2Property = new ReliableProperty<bool>(2, _isSolidPlayer2);
        _backupBoolProperty = new ReliableProperty<bool>(5, _backupBool);
        _backupFloatProperty = new ReliableProperty<float>(6, _backupFloat);
        _backupIntProperty = new ReliableProperty<int>(7, _backupInt);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _isSolidPlayer1Property.UnsubscribeCallback();
        _isSolidPlayer2Property.UnsubscribeCallback();
        _backupBoolProperty.UnsubscribeCallback();
        _backupFloatProperty.UnsubscribeCallback();
        _backupIntProperty.UnsubscribeCallback();
    }
    
    private void FireIsSolidPlayer1DidChange(bool value) {
        try {
            isSolidPlayer1DidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireIsSolidPlayer2DidChange(bool value) {
        try {
            isSolidPlayer2DidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireBackupBoolDidChange(bool value) {
        try {
            backupBoolDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireBackupFloatDidChange(float value) {
        try {
            backupFloatDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireBackupIntDidChange(int value) {
        try {
            backupIntDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _isSolidPlayer1Property.WriteLength(context);
        length += _isSolidPlayer2Property.WriteLength(context);
        length += _backupBoolProperty.WriteLength(context);
        length += _backupFloatProperty.WriteLength(context);
        length += _backupIntProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _isSolidPlayer1Property.Write(stream, context);
        writes |= _isSolidPlayer2Property.Write(stream, context);
        writes |= _backupBoolProperty.Write(stream, context);
        writes |= _backupFloatProperty.Write(stream, context);
        writes |= _backupIntProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.IsSolidPlayer1: {
                    changed = _isSolidPlayer1Property.Read(stream, context);
                    if (changed) FireIsSolidPlayer1DidChange(isSolidPlayer1);
                    break;
                }
                case (uint) PropertyID.IsSolidPlayer2: {
                    changed = _isSolidPlayer2Property.Read(stream, context);
                    if (changed) FireIsSolidPlayer2DidChange(isSolidPlayer2);
                    break;
                }
                case (uint) PropertyID.BackupBool: {
                    changed = _backupBoolProperty.Read(stream, context);
                    if (changed) FireBackupBoolDidChange(backupBool);
                    break;
                }
                case (uint) PropertyID.BackupFloat: {
                    changed = _backupFloatProperty.Read(stream, context);
                    if (changed) FireBackupFloatDidChange(backupFloat);
                    break;
                }
                case (uint) PropertyID.BackupInt: {
                    changed = _backupIntProperty.Read(stream, context);
                    if (changed) FireBackupIntDidChange(backupInt);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _isSolidPlayer1 = isSolidPlayer1;
        _isSolidPlayer2 = isSolidPlayer2;
        _backupBool = backupBool;
        _backupFloat = backupFloat;
        _backupInt = backupInt;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
